# Generated by Django 4.0.5 on 2023-01-03 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_complainttype_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='forget_password_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 11, 38, 30, 981381, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='complainttype',
            name='updation_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 11, 38, 30, 981381, tzinfo=utc), verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='tblecomplaint',
            name='complaint_regDate',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 11, 38, 30, 981381, tzinfo=utc), verbose_name='Complaint Submitted Date'),
        ),
    ]
